// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmymonzjfrirwxyqyqye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRteW1vbnpqZnJpcnd4eXF5cXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODc0ODMsImV4cCI6MjA2NjI2MzQ4M30.QZb6qq8ExToGfVbwwnIMsfoTWih0uez55Dfdp173mbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);